package com.skr.mrrdframe.repository.db.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.skr.mrrdframe.repository.db.entity.UploadFileInfo;

import com.skr.mrrdframe.repository.db.entity.UploadFileInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig uploadFileInfoDaoConfig;

    private final UploadFileInfoDao uploadFileInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        uploadFileInfoDaoConfig = daoConfigMap.get(UploadFileInfoDao.class).clone();
        uploadFileInfoDaoConfig.initIdentityScope(type);

        uploadFileInfoDao = new UploadFileInfoDao(uploadFileInfoDaoConfig, this);

        registerDao(UploadFileInfo.class, uploadFileInfoDao);
    }
    
    public void clear() {
        uploadFileInfoDaoConfig.clearIdentityScope();
    }

    public UploadFileInfoDao getUploadFileInfoDao() {
        return uploadFileInfoDao;
    }

}
